"""
Fully AI-powered Goal Advisor Service using OpenAI.
All analysis, suggestions, and recommendations are generated by AI.
"""
import json
import logging
from typing import List, Optional
from datetime import date
from uuid import UUID

from openai import AsyncOpenAI
from pydantic import BaseModel

from app.config import get_settings
from app.models.schemas import GoalData, TransactionData


class AIGoalAchievementPlan(BaseModel):
    """AI-generated plan to achieve a goal."""
    goal_id: UUID
    goal_name: str
    current_analysis: str
    achievement_probability: float  # 0-100
    recommended_monthly_saving: float
    time_to_achieve: str  # e.g., "6 months", "1 year"
    spending_cuts: List[dict]  # Categories to cut and amounts
    action_plan: List[str]  # Step-by-step actions
    risks: List[str]  # Potential risks to goal achievement
    motivational_insight: str


class AIGoalSuggestion(BaseModel):
    """AI-suggested goal based on spending analysis."""
    goal_type: str
    suggested_name: str
    suggested_target: float
    suggested_deadline: Optional[str] = None
    why_this_goal: str  # AI explanation
    how_to_achieve: str  # AI strategy
    priority: str
    confidence: float


class AITransactionImpact(BaseModel):
    """AI analysis of transaction impact on goals."""
    transaction_amount: float
    transaction_category: Optional[str]
    is_essential: bool
    impact_level: str  # HIGH, MEDIUM, LOW, NONE
    affected_goals: List[dict]  # Goals affected and how
    ai_verdict: str  # AI's opinion on this transaction
    alternative_suggestion: Optional[str]  # What user could do instead
    savings_opportunity: Optional[float]


class AISpendingWarning(BaseModel):
    """AI warning for unnecessary spending."""
    warning_type: str  # UNNECESSARY, EXCESSIVE, IMPULSE, RECURRING_WASTE
    severity: str  # HIGH, MEDIUM, LOW
    message: str
    affected_goals: List[str]
    potential_savings: float
    recommendation: str


class AIGoalAdvisor:
    """Fully AI-powered goal advisor using OpenAI."""

    def __init__(self):
        self.settings = get_settings()
        self.logger = logging.getLogger(__name__)
        self.client = None
        if self.settings.openai_api_key:
            self.client = AsyncOpenAI(api_key=self.settings.openai_api_key)

    def is_available(self) -> bool:
        return self.client is not None

    async def analyze_goal_achievement(
        self,
        goal: GoalData,
        transactions: List[TransactionData],
        all_goals: List[GoalData]
    ) -> AIGoalAchievementPlan:
        """AI analyzes how to achieve a specific goal based on spending patterns."""
        if not self.is_available():
            raise Exception("OpenAI is not configured. AI features require OpenAI API key.")

        # Prepare transaction summary
        txn_summary = self._prepare_transaction_summary(transactions)
        goals_context = self._prepare_goals_context(all_goals, goal.id)

        prompt = f"""You are an expert AI financial advisor. Analyze this user's spending and create a detailed plan to achieve their goal.

TARGET GOAL:
- Name: {goal.name}
- Type: {goal.goal_type}
- Target Amount: ₹{goal.target_amount:,.0f}
- Current Saved: ₹{goal.current_amount:,.0f}
- Remaining: ₹{goal.remaining_amount:,.0f}
- Deadline: {goal.deadline or 'Not set'}
- Days Remaining: {goal.days_remaining or 'N/A'}
- Currently On Track: {goal.is_on_track}

USER'S TRANSACTION HISTORY (Last 6 months):
{txn_summary}

OTHER ACTIVE GOALS:
{goals_context}

Analyze deeply and provide a JSON response:
{{
    "current_analysis": "2-3 sentences analyzing user's current financial situation relative to this goal",
    "achievement_probability": 0-100,
    "recommended_monthly_saving": amount in rupees,
    "time_to_achieve": "realistic time estimate",
    "spending_cuts": [
        {{"category": "category_name", "current_spending": amount, "suggested_cut": amount, "reason": "why"}}
    ],
    "action_plan": ["step 1", "step 2", "step 3", "step 4", "step 5"],
    "risks": ["risk 1", "risk 2"],
    "motivational_insight": "Personalized encouraging message"
}}

Be specific with amounts. Consider Indian context (UPI, SIPs, RDs). Be realistic but encouraging."""

        response = await self._call_openai(prompt)

        return AIGoalAchievementPlan(
            goal_id=goal.id,
            goal_name=goal.name,
            current_analysis=response.get("current_analysis", ""),
            achievement_probability=response.get("achievement_probability", 50),
            recommended_monthly_saving=response.get("recommended_monthly_saving", 0),
            time_to_achieve=response.get("time_to_achieve", "Unknown"),
            spending_cuts=response.get("spending_cuts", []),
            action_plan=response.get("action_plan", []),
            risks=response.get("risks", []),
            motivational_insight=response.get("motivational_insight", "")
        )

    async def suggest_goals(
        self,
        transactions: List[TransactionData],
        existing_goals: List[GoalData]
    ) -> List[AIGoalSuggestion]:
        """AI suggests new goals based on spending behavior analysis."""
        if not self.is_available():
            raise Exception("OpenAI is not configured.")

        txn_summary = self._prepare_transaction_summary(transactions)
        existing = [f"- {g.name} ({g.goal_type}): ₹{g.target_amount:,.0f}" for g in existing_goals if g.status == "ACTIVE"]

        prompt = f"""You are an AI financial advisor. Analyze this user's spending patterns and suggest personalized savings goals.

TRANSACTION HISTORY (Last 6 months):
{txn_summary}

EXISTING GOALS:
{chr(10).join(existing) if existing else "No active goals"}

Based on spending patterns, suggest 3-5 NEW goals that would benefit this user.
Consider:
1. Emergency fund if not present (6 months expenses)
2. Goals based on high spending categories (travel fund if travel spending is high)
3. Investment goals based on savings capacity
4. Life goals based on spending patterns (gadget fund, education, etc.)

Respond with JSON:
{{
    "suggested_goals": [
        {{
            "goal_type": "EMERGENCY/TRAVEL/GADGET/EDUCATION/INVESTMENT/HOME/VEHICLE/WEDDING/CUSTOM",
            "suggested_name": "Creative goal name",
            "suggested_target": amount in rupees,
            "suggested_deadline": "YYYY-MM-DD or null",
            "why_this_goal": "AI explanation of why this goal makes sense for this user",
            "how_to_achieve": "Specific strategy to achieve this goal",
            "priority": "HIGH/MEDIUM/LOW",
            "confidence": 0.0-1.0
        }}
    ]
}}

Be specific to THIS user's spending patterns. Indian context."""

        response = await self._call_openai(prompt)

        self.logger.info(f"OpenAI response for goal suggestions: {response}")

        suggestions = []
        suggested_goals = response.get("suggested_goals", [])

        if not suggested_goals:
            self.logger.warning(f"No suggested_goals in response. Full response: {response}")

        for s in suggested_goals:
            try:
                suggestions.append(AIGoalSuggestion(
                    goal_type=s.get("goal_type", "CUSTOM"),
                    suggested_name=s.get("suggested_name", ""),
                    suggested_target=float(s.get("suggested_target", 0)),
                    suggested_deadline=s.get("suggested_deadline"),
                    why_this_goal=s.get("why_this_goal", ""),
                    how_to_achieve=s.get("how_to_achieve", ""),
                    priority=s.get("priority", "MEDIUM"),
                    confidence=float(s.get("confidence", 0.7))
                ))
            except Exception as e:
                self.logger.error(f"Error parsing goal suggestion: {e}, data: {s}")
                continue

        self.logger.info(f"Parsed {len(suggestions)} goal suggestions")
        return suggestions

    async def analyze_transaction_impact(
        self,
        transaction_amount: float,
        transaction_category: Optional[str],
        transaction_description: Optional[str],
        goals: List[GoalData],
        recent_transactions: List[TransactionData]
    ) -> AITransactionImpact:
        """AI analyzes how a transaction affects user's goals."""
        if not self.is_available():
            raise Exception("OpenAI is not configured.")

        goals_summary = self._prepare_goals_context(goals)
        recent_spending = self._prepare_transaction_summary(recent_transactions[-50:] if len(recent_transactions) > 50 else recent_transactions)

        prompt = f"""You are an AI financial advisor. Analyze this transaction and its impact on user's goals.

TRANSACTION BEING ANALYZED:
- Amount: ₹{transaction_amount:,.0f}
- Category: {transaction_category or 'Unknown'}
- Description: {transaction_description or 'Not provided'}

USER'S ACTIVE GOALS:
{goals_summary}

RECENT SPENDING PATTERN:
{recent_spending}

Analyze this transaction and respond with JSON:
{{
    "is_essential": true/false,
    "impact_level": "HIGH/MEDIUM/LOW/NONE",
    "affected_goals": [
        {{"goal_name": "name", "impact": "How this transaction affects this goal", "delay_days": estimated days of delay}}
    ],
    "ai_verdict": "Your honest opinion about this transaction (2-3 sentences)",
    "alternative_suggestion": "What user could do instead to save money (or null if transaction is essential)",
    "savings_opportunity": amount that could be saved (or 0)
}}

Be honest but not judgmental. Consider Indian context."""

        response = await self._call_openai(prompt)

        return AITransactionImpact(
            transaction_amount=transaction_amount,
            transaction_category=transaction_category,
            is_essential=response.get("is_essential", True),
            impact_level=response.get("impact_level", "LOW"),
            affected_goals=response.get("affected_goals", []),
            ai_verdict=response.get("ai_verdict", ""),
            alternative_suggestion=response.get("alternative_suggestion"),
            savings_opportunity=response.get("savings_opportunity", 0)
        )

    async def get_spending_warnings(
        self,
        transactions: List[TransactionData],
        goals: List[GoalData]
    ) -> List[AISpendingWarning]:
        """AI identifies unnecessary spending that affects goals."""
        if not self.is_available():
            raise Exception("OpenAI is not configured.")

        txn_summary = self._prepare_transaction_summary(transactions)
        goals_summary = self._prepare_goals_context(goals)

        prompt = f"""You are an AI financial advisor. Analyze spending patterns and identify unnecessary expenses affecting goals.

TRANSACTION HISTORY (Last 6 months):
{txn_summary}

USER'S GOALS:
{goals_summary}

Identify spending patterns that are:
1. UNNECESSARY - Things user doesn't need
2. EXCESSIVE - Spending too much in a category
3. IMPULSE - Frequent small purchases adding up
4. RECURRING_WASTE - Subscriptions or recurring charges not being used

Respond with JSON:
{{
    "warnings": [
        {{
            "warning_type": "UNNECESSARY/EXCESSIVE/IMPULSE/RECURRING_WASTE",
            "severity": "HIGH/MEDIUM/LOW",
            "message": "Clear explanation of the issue",
            "affected_goals": ["goal names affected"],
            "potential_savings": monthly amount that could be saved,
            "recommendation": "Specific action to take"
        }}
    ],
    "overall_assessment": "2-3 sentence summary of spending health",
    "top_savings_opportunity": "The single biggest way to save money"
}}

Be specific with amounts. Indian context. Maximum 5 warnings, prioritize by impact."""

        response = await self._call_openai(prompt)

        warnings = []
        for w in response.get("warnings", []):
            warnings.append(AISpendingWarning(
                warning_type=w.get("warning_type", "UNNECESSARY"),
                severity=w.get("severity", "MEDIUM"),
                message=w.get("message", ""),
                affected_goals=w.get("affected_goals", []),
                potential_savings=w.get("potential_savings", 0),
                recommendation=w.get("recommendation", "")
            ))
        return warnings

    async def get_comprehensive_goal_advice(
        self,
        goals: List[GoalData],
        transactions: List[TransactionData]
    ) -> dict:
        """AI provides comprehensive advice for all goals."""
        if not self.is_available():
            raise Exception("OpenAI is not configured.")

        txn_summary = self._prepare_transaction_summary(transactions)
        goals_summary = self._prepare_goals_context(goals)

        prompt = f"""You are an expert AI financial advisor. Provide comprehensive advice for this user's financial goals.

USER'S GOALS:
{goals_summary}

TRANSACTION HISTORY (Last 6 months):
{txn_summary}

Provide a complete financial advisory response:
{{
    "financial_health_score": 0-100,
    "overall_assessment": "3-4 sentence assessment of user's financial health and goal progress",
    "goal_insights": [
        {{
            "goal_name": "name",
            "status": "ON_TRACK/AT_RISK/BEHIND/AHEAD",
            "insight": "Specific insight about this goal",
            "action_required": "What user should do",
            "projected_completion": "When they'll achieve it at current rate"
        }}
    ],
    "spending_analysis": {{
        "biggest_expense_category": "category",
        "unnecessary_spending": amount per month,
        "savings_potential": amount per month,
        "spending_trend": "INCREASING/DECREASING/STABLE"
    }},
    "recommendations": [
        {{
            "priority": "HIGH/MEDIUM/LOW",
            "title": "Short title",
            "description": "Detailed recommendation",
            "expected_impact": "What will happen if they follow this"
        }}
    ],
    "motivational_message": "Personalized encouraging message",
    "next_steps": ["Step 1", "Step 2", "Step 3"]
}}

Be specific, actionable, and encouraging. Indian financial context."""

        return await self._call_openai(prompt)

    def _prepare_transaction_summary(self, transactions: List[TransactionData]) -> str:
        """Prepare transaction summary for AI prompt."""
        if not transactions:
            return "No transaction data available."

        # Calculate totals by category
        income = sum(t.amount for t in transactions if t.direction == "CREDIT")
        expenses = sum(t.amount for t in transactions if t.direction == "DEBIT")

        category_totals = {}
        for t in transactions:
            if t.direction == "DEBIT":
                cat = t.category or "UNCATEGORIZED"
                category_totals[cat] = category_totals.get(cat, 0) + t.amount

        # Sort by amount
        sorted_cats = sorted(category_totals.items(), key=lambda x: x[1], reverse=True)

        lines = [
            f"Total Income: ₹{income:,.0f}",
            f"Total Expenses: ₹{expenses:,.0f}",
            f"Net Savings: ₹{income - expenses:,.0f}",
            f"Savings Rate: {((income - expenses) / income * 100) if income > 0 else 0:.1f}%",
            "",
            "Spending by Category:"
        ]
        for cat, amount in sorted_cats[:10]:
            pct = (amount / expenses * 100) if expenses > 0 else 0
            lines.append(f"  - {cat}: ₹{amount:,.0f} ({pct:.1f}%)")

        return "\n".join(lines)

    def _prepare_goals_context(self, goals: List[GoalData], exclude_id: UUID = None) -> str:
        """Prepare goals context for AI prompt."""
        if not goals:
            return "No goals set."

        lines = []
        for g in goals:
            if exclude_id and g.id == exclude_id:
                continue
            if g.status == "ACTIVE":
                status = "✓ On Track" if g.is_on_track else "⚠ Needs Attention"
                deadline = f", Deadline: {g.deadline}" if g.deadline else ""
                lines.append(
                    f"- {g.name} ({g.goal_type}): ₹{g.current_amount:,.0f}/₹{g.target_amount:,.0f} "
                    f"({g.progress_percent:.0f}%){deadline} - {status}"
                )
        return "\n".join(lines) if lines else "No active goals."

    async def _call_openai(self, prompt: str) -> dict:
        """Call OpenAI API and return parsed JSON response."""
        self.logger.info("=" * 50)
        self.logger.info("OPENAI API CALL STARTED")
        self.logger.info(f"Model: {self.settings.openai_model}")
        self.logger.info(f"Temperature: {self.settings.openai_temperature}")
        self.logger.info(f"Prompt length: {len(prompt)} characters")
        self.logger.debug(f"Full prompt:\n{prompt[:500]}...")  # First 500 chars

        try:
            self.logger.info("Sending request to OpenAI...")
            response = await self.client.chat.completions.create(
                model=self.settings.openai_model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are an expert Indian financial advisor with deep knowledge of personal finance, savings strategies, and Indian financial instruments (SIPs, FDs, RDs, PPF, NPS). Provide accurate, actionable, and encouraging advice. Always respond with valid JSON."
                    },
                    {"role": "user", "content": prompt}
                ],
                temperature=self.settings.openai_temperature,
                max_tokens=2000,
                response_format={"type": "json_object"}
            )

            raw_content = response.choices[0].message.content
            self.logger.info("OPENAI RESPONSE RECEIVED")
            self.logger.info(f"Response length: {len(raw_content)} characters")
            self.logger.info(f"Usage - Prompt tokens: {response.usage.prompt_tokens}, Completion tokens: {response.usage.completion_tokens}")
            self.logger.info(f"Raw response:\n{raw_content}")

            parsed = json.loads(raw_content)
            self.logger.info(f"Parsed JSON keys: {list(parsed.keys())}")
            self.logger.info("=" * 50)

            return parsed
        except json.JSONDecodeError as e:
            self.logger.error(f"JSON parsing error: {e}")
            self.logger.error(f"Raw content that failed to parse: {raw_content}")
            raise Exception(f"AI response parsing error: {str(e)}")
        except Exception as e:
            self.logger.error(f"OpenAI API error: {type(e).__name__}: {e}")
            self.logger.info("=" * 50)
            raise Exception(f"AI service error: {str(e)}")


# Singleton instance
ai_goal_advisor = AIGoalAdvisor()

